import { createRepository } from "./repository-manager";

export async function bootstrapProject(name: string): Promise<void> {
  await createRepository({
    name,
    visibility: "public",
    labels: ["dragon", "autogenerated"]
  });
}